### ISSUE TITLE
fix: specified URLs should be normalized

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/vexhub-crawler#27]
## Description
If `url` is passed as below, `vexhub-crawler` will not try to detect the source repository and instead [use the URL](https://github.com/aquasecurity/vexhub-crawler/blob/f2ae941962bb58e453f3a9adb8b85f61dcc19a34/pkg/crawl/crawl.go#L65-L72)

```yaml
  golang:
    - namespace: github.com/rancher
       name: rancher
       url: https://github.com/rancher/vexhub/tree/main/pkg/golang/github.com/rancher
```

However, the URL is not normalized now. We need to call [NormalizeURL](https://github.com/aquasecurity/vexhub-crawler/blob/f2ae941962bb58e453f3a9adb8b85f61dcc19a34/pkg/crawl/git/url.go#L12) for the passed URL.

```golang
	src := pkg.URL
	if src != "" {
		normalized, err := git.NormalizeURL(src)
		if err != nil {...}
		src = normalized
	} else {
		detected, err := crawler.DetectSrc(ctx, pkg)
		if err != nil {...}
		src = detected
	}
```
